// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAooMkEfipR1nnZ2LkP-4_mpwqN360KGHc',
    appId: '1:148259558363:android:6af0497ef6bc66476b0dfe',
    messagingSenderId: '148259558363',
    projectId: 'evently-d79e1',
    storageBucket: 'evently-d79e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPkGzccoocpPKREs4vq0rYdkdLCC808n0',
    appId: '1:148259558363:ios:c0b73e95d493b03b6b0dfe',
    messagingSenderId: '148259558363',
    projectId: 'evently-d79e1',
    storageBucket: 'evently-d79e1.firebasestorage.app',
    iosBundleId: 'com.route.eventlyC17',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPkGzccoocpPKREs4vq0rYdkdLCC808n0',
    appId: '1:148259558363:ios:153a995bc4ff606a6b0dfe',
    messagingSenderId: '148259558363',
    projectId: 'evently-d79e1',
    storageBucket: 'evently-d79e1.firebasestorage.app',
    iosBundleId: 'r',
  );
}
